-- Referencia documental simplificada del esquema inicial de producción base.
-- La fuente de verdad para el modelo actual es `prisma/schema.prisma`
-- y la migración versionada vive en `prisma/migrations/0001_init/migration.sql`.
